# Generated by Django 4.2.2 on 2025-03-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT')], default=None, max_length=50, null=True),
        ),
    ]
